### ISSUE TITLE
Bored API

### ISSUE THREAD

**Issue by cbmartinez42** [cbmartinez42/boredify-project#7]
https://www.boredapi.com/

Start with Random for MVP, then we can add additional options such as number of participants, etc

http://www.boredapi.com/api/activity/

Response:
{
	"activity": "Learn Express.js",
	"accessibility": 0.25,
	"type": "education",
	"participants": 1,
	"price": 0.1,
	"link": "https://expressjs.com/",
	"key": "3943506"
} 

Query for activity and type

**Comment by SLUDGE-GIT** [comment]
implemented
