### ISSUE TITLE
RobotHash API

### ISSUE THREAD

**Issue by cbmartinez42** [cbmartinez42/boredify-project#8]
https://robohash.org/

MVP:
all we need to do is code in the url and insert whatever characters they input at the end of their url. 

For further development:
You can add things like ?set=set2 to specify monsters, cats, etc. do we want to have these as an optional radio button?

You are free to embed under the terms of the CC-BY license.
Example wording might be "Robots lovingly delivered by Robohash.org" or something.

**Comment by cbmartinez42** [comment]
Mostly done. Still need to get the input form working so I can properly see what I'm working with. need to add button to get another avatar. 

If time allows, will allow selection of alternate avatars - monster, cat, etc

**Comment by SLUDGE-GIT** [comment]
implemented
